language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements-dev.txt -r requirements.txt
- pip install codecov
scripts:
- nosetests --with-coverage --cover-package=nginx_pilot_api
- codecov
env:
  global:
  - FLASK_SECRET_KEY=asecretkeyusedfortestingpurposeonly
  - secure: jXrSi3GxeyWLTDEJP+jrCt9kUVuAbK1edt51kqTjTFaLh17q4U41hmpFlSj3RrNNqXx3KqJvEreqkh6iwWHtECo1CrcuQuPJweMY0b/k+sIs7/cbYjv9j+BrwPtk1pmU4enUIpllxV2QC5V+P2MXaCDD0oDsTLdpEFdTMrQnDQnDTZUROG8/cre/n+VWAcUpEzo7r1lErujzEn2AF6CF0RoEG0XooeYqGchlhy0OcszKiCl2zkuhb05Yj2db+558VX1CvJ2KldEUGexE4ZAsI/aL35dECI+MdAP1bSjyKWXmNkhxgUMfqXla11wcbwltCgM4JWm6Hh7quAbEkL7VRBVfQoZ3K3yQLpcB14kyXwdj6Ge7TfchmDYq0mOhPflILCE7jv37kSXuRX3bDh9JgH9MWkJnWRh0RsbUrsJxsNz40cHTi0qD8YsXNpoJDYWNX/KpDP2vD2u9SEktz2lwsuvI5dZG4udSgqOhsGOEG+c0VjG7WLhTggeYrLneUJ+xUzz4EpXoNth+aVOkiAw8ZKyl2p77b92xthcAOjuSm4zqZUQlGlq7Wy8PikcsqDobyrHDULmQEcoY0FWCvddUQc6llsC7ugJ3dL/e+sdTQhb5aC5YJqmnuzxMJYyf7nuRhSdYtotmjw7uRycFmcI7HfY8ntZ7zPOKW6HrCzHHSAo=
