language: python
python:
- '3.4'
- '3.5'
- '3.6'
before_install:
  - pip install codecov
install:
- pip install -r requirements-dev.txt -r requirements.txt
scripts:
- nosetests --with-coverage --cover-package=nginx_pilot_api
- codecov
env:
  global:
  - FLASK_SECRET_KEY=asecretkeyusedfortestingpurposeonly
  - secure: "bspnYjfTnDbMbguQK8Zi0hflqaT003Yjok/PbP27n10m3gye8pgWs4fLTh4hBBCiLQUEurd/EzGNju3Cde/NaocpUurPHUld4VOXM9zs+8H1gC4s5WyGDNI35ibvOM+dKEURN7HvKnY5b7giqMXhXR7uAbGrm6hM+jYjcV0jCQM/lAsVO8PypT1YuXp53GMm44sjenUrOHHlbRkrtt1KxCvCeG6qTSCL7VwIQvs7rqngG6Q42FNupiqiaWOJqSHZzQ7rBVWMMyp1DMC+qCDPuFg7FclhHLu/fp5y88XmfuSk7XnOt/ty4ze+2Vi9CJzwzHvw+R7ZIFzBcaRgKOHc8r3uc+KLmiHD6mmNQHlckGwO/+syHB/FgtJey/t2npDxq7eIUFJsk5A1+9b4bnIJvFEDhXl7rtKIlg/hlGw9ormWKMJMppLlkU9wD924fAPeIYcodyTxiq/8tGlb5PdyxMud5RUcS+MKCN+reay+tge4yEQOfiJvNTKeFq9ELBDxssqsQXCir/SbhLvTunCmHw2dnsTVEwK1DqCQvZYM3tXy7E3BfByOwx70Jy8os1raxQY+FFjJGwuAvWG7kk2Iq48pY2Eg45way6nS3c3VZYFE1tunwfIS/shRBtcwRRm+Cyim7vR+IJmdiHsXG2EAPvr4FCzb6nXqiN1qaCNrrxg="
